// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://aeziqdbbztpfrjzlggml.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlemlxZGJienRwZnJqemxnZ21sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NjM3MTAsImV4cCI6MjA3NjAzOTcxMH0.8Qu1n79VsxA1ROkDXK4cQNUX8zlGzxM8c3L77oAzEek';

// Debug environment loading
console.log('Environment variables loaded:');
console.log('- From env VITE_SUPABASE_URL:', import.meta.env.VITE_SUPABASE_URL);
console.log('- Using SUPABASE_URL:', SUPABASE_URL);
console.log('- Environment keys available:', Object.keys(import.meta.env));

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'resume-builder-app',
    },
  },
});